"""initial tables

Revision ID: 58300af3fd36
Revises: 
Create Date: 2026-03-21 21:56:26.220682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '58300af3fd36'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=False),
    sa.Column('synthesis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_ideas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('previous_session_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('publication_number', sa.String(length=50), nullable=True),
    sa.Column('patent_link', sa.Text(), nullable=True),
    sa.Column('priority_date', sa.Date(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('inventor', sa.Text(), nullable=True),
    sa.Column('assignee', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('innovations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('patent_id', sa.Integer(), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=True),
    sa.Column('innovation_summary', sa.Text(), nullable=True),
    sa.Column('technology_used', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('problem_solved', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('innovations')
    op.drop_table('patents')
    op.drop_table('analyses')
    # ### end Alembic commands ###
